version: "3.8"
services:
  keycloak-database:
    image: postgres:latest
    container_name: code_recipe_keycloak_db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./db/keycloakDB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "keycloak"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "-p 5433"
    networks:
      code_recipe:
        aliases:
          - "keycloak_db"
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: code_recipe_keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5433/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "8080:8080"
    command: start-dev
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
    depends_on:
      keycloak-database:
        condition: service_started
    networks:
      code_recipe:
        aliases:
          - "keycloak"

networks:
  code_recipe:
    driver: bridge