version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: code_recipe_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "coderecipe_dev"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      code_recipe:
        aliases:
          - "database"
  keycloak:
    image: quay.io/keycloak/keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    healthcheck:
        test: "curl -f http://localhost:8080/admin || exit 1"
    networks:
      code_recipe:
        aliases:
          - "keycloak"


networks:
  code_recipe:
    driver: bridge
