version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: code_recipe_db
    domainname: database
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "coderecipe_dev"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      code_recipe:
        aliases:
          - "database"

  configserver:
    image : "junseokee/config-server:0.0.1-SNAPSHOT"
    domainname: configserver
    container_name: code_recipe_config_server
    ports:
      - "8071:8071"
    networks:
      code_recipe:
        aliases:
          - "configserver"

  eurekaserver:
    image : "junseokee/eureka-server:0.0.1-SNAPSHOT"
    domainname: eurekaserver
    container_name: code_recipe_eureka_server
    ports :
      - "8761:8761"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      CONFIG_SERVER_URL: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      code_recipe:
        aliases:
          - "eurekaserver"

  gatewayserver:
    image : "junseokee/gateway-server:0.0.1-SNAPSHOT"
    domainname: gatewayserver
    container_name: code_recipe_gateway_server
    ports :
      - "8000:8000"
    environment:
      SPRING_PROFILE_ACTIVE: dev
      CONFIG_SERVER_URL: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      code_recipe:
        aliases:
          - "gateway"

  cardservice:
    image : "junseokee/card-service:0.0.1-SNAPSHOT"
    domainname: cardservice
    container_name: code_recipe_card_service
    environment:
      SPRING_PROFILE_ACTIVE: dev
      CONFIG_SERVER_URL: http://configserver:8071
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      code_recipe:



networks:
  code_recipe:
    driver: bridge
