spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    config:
      name: user-service
      profile: ${SPRING_PROFILE_ACTIVE}