server:
  port: 8000

spring:
  application:
    name: gateway-server
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN