spring:
  application:
    name: config-server
  profiles:
    active: native #, git, vault
  cloud:
    config:
      server:
        encrypt.enabled: false
        native:
          search-locations: classpath:/config
#        git:
#          uri: https://github.com/klimtever/config.git
#          searchPaths: licensingservice
#        vault:
#          port: 8200
#          host: 127.0.0.1
#          kvVersion: 2
#          profile-separator: /
#          backend: licensing-service
server:
  port: 8071


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"