server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    loadbalancer:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false