server:
  port: 8082

spring:
  application:
    name: receipt-service
  config:
    import: vault://
  cloud:
    vault:
      scheme: http
      host: 34.22.82.97
      port: 8200
      authentication: KUBERNETES
      kubernetes:
        role: app
        kubernetes-path: kubernetes
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kv:
        enabled: true
        backend: secret
        default-context: bibot
        profiles:
          - db
          - ocr
          - cloak
          - jwt
    gcp:
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
      storage:
        enabled: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${host_name}/receipt
    username: ${db_name}
    password: ${db_pwd}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      platform: postgres

  kafka:
    bootstrap-servers: ${kafka_url}
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${jwk_uri}
          issuer-uri: ${iss_uri}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}

gcp:
  bucket:
    name: bibot_receipt

jwt:
  auth:
    converter:
      resource-id: bibot
      principal-attribute: preferred_username

ocr-api-secret: ${ocr_token}

ocr-api-url: ${ocr_url}


management:
  endpoints:
    web:
      exposure:
        include: "*"



#  datasource:
#    write:
#      driver-class-name: org.postgresql.Driver
#      jdbcUrl: jdbc:postgresql://${master_host}/users
#      username: ${master_name}
#      password: ${master_pwd}
#
#    read:
#      driver-class-name: org.postgresql.Driver
#      jdbcUrl: jdbc:postgresql://${slave_host}/users
#      username: ${slave_name}
#      password: ${slave_pwd}