spring:
  application:
    name: receipt-service
  datasource:
    url: jdbc:postgresql://34.64.101.34:5432/bibot
    username: "coderecipe"
    password: "codekunst"
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  sql:
    init:
      platform: postgres
  output:
    ansi:
      enabled: always